#Esse arquivo faz o mesmo trabalho do application.properties
#porém traz uma forma mais fácil de entender
#O application é como se fosse a central de configuração do spring
#Nele posso definir config como: banco de dados, porta do servidor, logs, etc...

spring:
  application:
    name: sistemaos
  datasource:
    url: jdbc:mysql://localhost:3306/bike_facil
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 93fff04c5d8041
    password: 39664621df924b
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  app:
    base-url: https://trimness-unlocked-skintight.ngrok-free.dev

