# Esse arquivo faz o mesmo trabalho do application.properties
# porém traz uma forma mais fácil de entender
# O application é como se fosse a central de configuração do Spring
# Nele posso definir configurações como: banco de dados, porta do servidor, logs, etc.

server:
  servlet:
    #context-path: /pmanager
  port: 8080
spring:
  jackson:
    default-property-inclusion: non_null  #isso aqui é para remover da requisição de valores nulos.
  application:
    name: pmanager
  datasource:
    url: jdbc:h2:mem:teste
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 81727d096850b2Xcv]
    password: 2443dca28eb62a
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  app:
    base-url: https://trimness-unlocked-skintight.ngrok-free.dev